//-------- GET para USERS

GET http://localhost:3000/api/users/all
authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBEYXRlIjoxNjU4OTExNjMxLCJpYXQiOjE2NTg0Nzk2MzF9.EekNZVLXOoWqlywQGA8fgDi8w0ZCb_f2nNVeQlcypd8"

###

GET http://localhost:3000/api/users/10
authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBEYXRlIjoxNjU4OTEyMTk2LCJpYXQiOjE2NTg0ODAxOTZ9.a7GlmhU6E7eQQ2FQjlRFF7WMi3ka_i8-eyURovS51ho"

###

GET http://localhost:3000/api/users/email/lolosg@gmail.com

###
GET http://localhost:3000/api/users/user/lolosoloyolo

###


//---------------POST para USERS-----------------//

//register

POST http://localhost:3000/api/new/register
Content-Type: application/json

{  
    "name": "Alberto",
    "surname": "Sanchez",
    "username": "nihablarpeluca",
    "email": "sanchezalbert@gmail.com",
    "password": "12345"
}

###

// --------- login users (new) ---------//

POST http://localhost:3000/api/new/login
Content-Type: application/json

{
    "email": "lolosg@gmail.com",
    "password": "12345"
}

###

//-------------UPDATE para USERS----------------//

// (en postman porque tengo que subir archivos)






###

//--------------DELETE para USERS---------------//

DELETE http://localhost:3000/api/users/delete/8










