//-------- GET para USERS

GET http://localhost:3000/api/users/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBEYXRlIjoxNjU4OTEyNTU3LCJpYXQiOjE2NTg0ODA1NTd9.jPRHgd-TT6LwNUCUERqz8R5kPVzP2o71uCrKpVF2Mfg

###

GET http://localhost:3000/api/users/10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBEYXRlIjoxNjU4OTEyNTU3LCJpYXQiOjE2NTg0ODA1NTd9.jPRHgd-TT6LwNUCUERqz8R5kPVzP2o71uCrKpVF2Mfg

###

GET http://localhost:3000/api/users/email/lolosg@gmail.com

###
GET http://localhost:3000/api/users/user/lolosoloyolo

###


//---------------POST para USERS-----------------//

//register

POST http://localhost:3000/api/new/register
Content-Type: application/json

{  
    "name": "Alberto",
    "surname": "Sanchez",
    "username": "nihablarpeluca",
    "email": "sanchezalbert@gmail.com",
    "password": "12345"
}

###

// --------- login users (new) ---------//

POST http://localhost:3000/api/new/login
Content-Type: application/json

{
    "email": "lolosg@gmail.com",
    "password": "12345"
}

###

//-------------UPDATE para USERS----------------//

// (en postman porque tengo que subir archivos)






###

//--------------DELETE para USERS---------------//

DELETE http://localhost:3000/api/users/delete/8










